export const ventureDetails = [
  {
    name: "Unity Capital Ventures",
    logo: "https://unitycapitalvc.com/assets/theme-assets/images-3d-animation/uniticapitial.png",
    description:
      "Unity Capital Ventures is a venture capital firm that invests in early-stage startups in the blockchain and crypto space.",
    socials: {
      website: "https://unitycapitalvc.com/",
      twitter: "sf",
      facebook: "",
      instagram: "daf",
      telegram: "",
    },
  },
  {
    name: "Oddiyyana Ventures",
    logo: "./images/oddiyana.jpeg",
    description:
      "Oddiyyana Ventures is a venture capital firm that invests in early-stage startups in the blockchain and crypto space.",
    socials: {
      website: "https://oddiyana.ventures/",
      twitter: "",
      facebook: "sdsaf",
      instagram: "dafj",
      telegram: "saf",
    },
  },
  {
    name: "V2B Labs",
    logo: "https://www.v2blabs.com/_nuxt/img/Logo.6837bc2.png",
    description:
      "V2B Labs is a venture capital firm that invests in early-stage startups in the blockchain and crypto space.",
    socials: {
      website: "https://www.v2blabs.com/",
      twitter: "dfadf",
      facebook: "",
      instagram: "",
      telegram: "asdf",
    },
  },
  {
    name: "BMW Capital",
    logo: "images/bmwcapital.png",
    description:
      "BMW Capital is a venture capital firm that invests in early-stage startups in the blockchain and crypto space.",
    socials: {
      website: "http://www.bmw-vc.com/",
      twitter: "",
      facebook: "",
      instagram: "dfajkl",
      telegram: "df",
    },
  },
  {
    name: "Zephyrus Capital",
    logo: "https://zephyruscapital.com/wp-content/uploads/2021/12/logowhite.png",
    description:
      "Zephyrus Capital is a venture capital firm that invests in early-stage startups in the blockchain and crypto space.",
    socials: {
      website: "https://zephyruscapital.com/",
      twitter: "",
      facebook: "dsafa",
      instagram: "dsaf",
      telegram: "",
    },
  },
  {
    name: "Unreal Capital",
    logo: "https://static.tildacdn.com/tild3834-3661-4463-b238-393837653962/UnrealCapital_logo_v.svg",
    description:
      "Unreal Capital is a venture capital firm that invests in early-stage startups in the blockchain and crypto space.",
    socials: {
      website: "https://ucapital.vc/",
      twitter: "",
      facebook: "dfajd",
      instagram: "",
      telegram: "sfa",
    },
  },
  {
    name: "Next Capital",
    logo: "/images/NEXTWHTWIDE.svg",
    description:
      "Next Capital is a venture capital firm that invests in early-stage startups in the blockchain and crypto space.",
    socials: {
      website: "https://www.nextcapital.tech/",
      twitter: "dafls",
      facebook: "dfad",
      instagram: "",
      telegram: "dsaf",
    },
  },
  {
    name: "Cogitent Ventures",
    logo: "/images/cogitent.png",
    description:
      "Cogitent Ventures is a venture capital firm that invests in early-stage startups in the blockchain and crypto space.",
    socials: {
      website: "https://cogitent.ventures/",
      twitter: "fjda",
      facebook: "",
      instagram: "",
      telegram: "",
    },
  },
];

export const portfolioDetails = [
  {
    name: "Aether Games",
    logo: "https://www.aethergames.io/static/media/Logo.6d355d0b397d1925df34.png",
    description: "Aether Games is a blockchain-based gaming platform.",
    socials: {
      website: "https://www.aethergames.io/",
      twitter: "sf",
      facebook: "",
      instagram: "daf",
      telegram: "",
    },
  },
  {
    name: "Playzap Games",
    logo: "https://uploads-ssl.webflow.com/622b71d5703c41011dd1c3ac/623294d6f64369568f797a85_footer-logo.png",
    description: "Playzap Games is a blockchain-based gaming platform.",
    socials: {
      website: "https://www.playzap.games/",
      twitter: "",
      facebook: "sdsaf",
      instagram: "dafj",
      telegram: "saf",
    },
  },
  {
    name: "Magpie",
    logo: "https://uploads-ssl.webflow.com/629b39872d72ff02443a529f/629b4145d174c694099716c5_Logo.svg",
    description:
      'Magpie is a "decentralized, open-source, and community-driven" NFT marketplace.',
    socials: {
      website: "https://www.magpiefi.xyz/",
      twitter: "dfadf",
      facebook: "",
      instagram: "",
      telegram: "asdf",
    },
  },
  {
    name: "Web3Port",
    logo: "images/web3port.png",
    description: "Web3Port is a blockchain-based gaming platform.",
    socials: {
      website: "https://www.web3port.us/",
      twitter: "",
      facebook: "",
      instagram: "dfajkl",
      telegram: "df",
    },
  },
  {
    name: "Astra Protocol",
    logo: "https://astraprotocol.com/wp-content/themes/astra_wp/assets/images/logo.svg",
    description: "Astra Protocol is a blockchain-based gaming platform.",
    socials: {
      website: "https://astraprotocol.com/",
      twitter: "",
      facebook: "dsafa",
      instagram: "dsaf",
      telegram: "",
    },
  },
  {
    name: "Tatsumeeko",
    logo: "images/tatsumeeko.png",
    description: "Tatsumeeko is a blockchain-based gaming platform.",
    socials: {
      website: "https://tatsumeeko.com/",
      twitter: "",
      facebook: "dfajd",
      instagram: "",
      telegram: "sfa",
    },
  },
  {
    name: "BitsCrunch",
    logo: "https://bitscrunch.com/wp-content/themes/bitscrunch/img/logo.svg",
    description: "BitsCrunch is a blockchain-based gaming platform.",
    socials: {
      website: "https://bitscrunch.com/",
      twitter: "dafls",
      facebook: "dfad",
      instagram: "",
      telegram: "dsaf",
    },
  },
  {
    name: "Peaq Network",
    logo: "images/peaq.png",
    description: "Peaq Network is a blockchain-based gaming platform.",
    socials: {
      website: "https://www.peaq.network/",
      twitter: "fjda",
      facebook: "",
      instagram: "",
      telegram: "",
    },
  },
  {
    name: "ZKCross",
    logo: "images/zkcr.png",
    description: "ZKCross is a blockchain-based gaming platform.",
    socials: {
      website: "https://www.zkcross.org/",
      twitter: "fjda",
      facebook: "",
      instagram: "",
      telegram: "",
    },
  },
  {
    name: "Humanode",
    logo: "images/Humanode.png",
    description: "Humanode is a blockchain-based gaming platform.",
    socials: {
      website: "https://humanode.io/",
      twitter: "fjda",
      facebook: "",
      instagram: "",
      telegram: "",
    },
  },
  {
    name: "Magic Square",
    logo: "https://magicsquare.io/wp-content/uploads/2022/09/MSQ-Logo-color.svg",
    description: "Magic Square is a blockchain-based gaming platform.",
    socials: {
      website: "https://magicsquare.io/",
      twitter: "fjda",
      facebook: "",
      instagram: "",
      telegram: "",
    },
  },
  {
    name: "Cosmic Guild",
    logo: "images/Cosmic.png",
    description: "Cosmic Guild is a blockchain-based gaming platform.",
    socials: {
      website: "https://cosmicguild.io/",
      twitter: "",
      facebook: "dfa",
      instagram: "",
      telegram: "dsaf",
    },
  },
  {
    name: "BlueMove",
    logo: "https://bluemove.net/static/media/logo-light.9e42d613ce273b89f8bd87d58adee26a.svg",
    description: "BlueMove is a blockchain-based gaming platform.",
    socials: {
      website: "https://bluemove.net/",
      twitter: "",
      facebook: "dfa",
      instagram: "",
      telegram: "dsaf",
    },
  },
  {
    name: "Mover",
    logo: "images/Mover.png",
    description: "Mover is a blockchain-based gaming platform.",
    socials: {
      website: "https://mov3r.xyz/",
      twitter: "",
      facebook: "dfa",
      instagram: "saf",
      telegram: "dsaf",
    },
  },
  {
    name: "Exorde Network",
    logo: "https://uploads-ssl.webflow.com/620398f412d5829aa28fbb86/622625f35016cd6a5613f833_landscape-logo-color-white.png",
    description: "Exorde Network is a blockchain-based gaming platform.",
    socials: {
      website: "https://exorde.network/",
      twitter: "",
      facebook: "dfa",
      instagram: "saf",
      telegram: "dsaf",
    },
  },

  {
    name: "Alterverse",
    logo: "https://alterverse.com/wp-content/uploads/2021/01/AlterVerseLogo_Lg_White_NoStroke_400.png",
    description: "Alterverse is a blockchain-based gaming platform.",
    socials: {
      website: "https://alterverse.com/",
      twitter: "dasfd",
      facebook: "dfa",
      instagram: "saf",
      telegram: "dsaf",
    },
  },

  {
    name: "Entangle Finance",
    logo: "images/entangle.png",
    description: "Entangle Finance is a blockchain-based gaming platform.",
    socials: {
      website: "https://entangle.fi/",
      twitter: "",
      facebook: "dfa",
      instagram: "saf",
      telegram: "dsaf",
    },
  },
];

export const partnerDetails = [
  {
    name: "Celer Network",
    logo: "images/celer.png",
    description: "Celer Network is a blockchain-based gaming platform.",
    socials: {
      website: "https://cbridge.celer.network/137/56/ANML",
      twitter: "",
      facebook: "dfa",
      instagram: "saf",
      telegram: "dsaf",
    },
  },
  {
    name: "China Polka",
    logo: "images/chinapolka.png",
    description: "China Polka is a blockchain-based gaming platform.",
    socials: {
      website: "http://chinapolka.com/",
      twitter: "",
      facebook: "dfa",
      instagram: "saf",
      telegram: "dsaf",
    },
  },
  {
    name: "Polygon",
    logo: "images/polygon.png",
    description: "Polygon is a blockchain-based gaming platform.",
    socials: {
      website: "https://polygon.technology/",
      twitter: "",
      facebook: "dfa",
      instagram: "saf",
      telegram: "dsaf",
    },
  },
  {
    name: "TomoChain",
    logo: "images/tmochain.svg",
    description: "TomoChain is a blockchain-based gaming platform.",
    socials: {
      website: "https://tomochain.com/",
      twitter: "",
      facebook: "dfa",
      instagram: "saf",
      telegram: "dsaf",
    },
  },
  {
    name: "Casper Labs",
    logo: "images/casper.png",
    description: "Casper Labs is a blockchain-based gaming platform.",
    socials: {
      website: "https://casperlabs.io/",
      twitter: "",
      facebook: "",
      instagram: "saf",
      telegram: "dsaf",
    },
  },
  {
    name: "Certik",
    logo: "https://movenetwork.io/wp-content/uploads/2021/11/Certik-logo-300x300-01.png",
    description: "Certik is a blockchain-based gaming platform.",
    socials: {
      website: "https://certik.com/",
      twitter: "",
      facebook: "dfa",
      instagram: "saf",
      telegram: "dsaf",
    },
  },
  {
    name: "Hacken",
    logo: "https://s2.coinmarketcap.com/static/img/coins/200x200/5583.png",
    description: "Hacken is a blockchain-based gaming platform.",
    socials: {
      website: "https://hacken.io/",
      twitter: "",
      facebook: "dfa",
      instagram: "saf",
      telegram: "dsaf",
    },
  },
  {
    name: "Deeper Network",
    logo: "images/deeper.png",
    description: "Deeper Network is a blockchain-based gaming platform.",
    socials: {
      website: "https://deeper.network/",
      twitter: "",
      facebook: "dfa",
      instagram: "saf",
      telegram: "dsaf",
    },
  },
  {
    name: "Labs Group",
    logo: "images/labsgroup.png",
    description: "Labs Group is a blockchain-based gaming platform.",
    socials: {
      website: "https://labsgroup.io/",
      twitter: "",
      facebook: "dfa",
      instagram: "",
      telegram: "dsaf",
    },
  },
  {
    name: "Koi Starter",
    logo: "images/koistarter.svg",
    description: "Koi Starter is a blockchain-based gaming platform.",
    socials: {
      website: "https://koistarter.io/",
      twitter: "",
      facebook: "dfa",
      instagram: "saf",
      telegram: "dsaf",
    },
  },
  {
    name: "Harmony Launcher",
    logo: "images/harmony-launcher.jpg",
    description: "Harmony Launcher is a blockchain-based gaming platform.",
    socials: {
      website: "https://harmonylauncher.io/",
      twitter: "fdsf",
      facebook: "dfa",
      instagram: "saf",
      telegram: "dsaf",
    },
  },
  {
    name: "Kommunitas",
    logo: "images/kommunitas.png",
    description: "Kommunitas is a blockchain-based gaming platform.",
    socials: {
      website: "https://kommunitas.net/",
      twitter: "",
      facebook: "dfa",
      instagram: "saf",
      telegram: "dsaf",
    },
  },
  {
    name: "Fantom Live",
    logo: "images/fantomlive.png",
    description: "Fantom Live is a blockchain-based gaming platform.",
    socials: {
      website: "https://fantomlive.finance/",
      twitter: "",
      facebook: "dfa",
      instagram: "saf",
      telegram: "dsaf",
    },
  },
  {
    name: "Unifarm",
    logo: "images/unifarm.jpg",
    description: "Unifarm is a blockchain-based gaming platform.",
    socials: {
      website: "https://unifarm.co/",
      twitter: "",
      facebook: "dfa",
      instagram: "saf",
      telegram: "dsaf",
    },
  },
  {
    name: "Ankr",
    logo: "images/ankr.png",
    description: "Ankr is a blockchain-based gaming platform.",
    socials: {
      website: "https://ankr.com/",
      twitter: "",
      facebook: "dfa",
      instagram: "saf",
      telegram: "dsaf",
    },
  },
  {
    name: "Unilend",
    logo: "images/unilend.png",
    description: "Unilend is a blockchain-based gaming platform.",
    socials: {
      website: "https://unilend.finance/",
      twitter: "",
      facebook: "dfa",
      instagram: "saf",
      telegram: "dsaf",
    },
  },
  {
    name: "Dfyn Network",
    logo: "images/dfyn.png",
    description: "Dfyn Network is a blockchain-based gaming platform.",
    socials: {
      website: "https://dfyn.network/",
      twitter: "",
      facebook: "dfa",
      instagram: "saf",
      telegram: "dsaf",
    },
  },
  {
    name: "Public Mint",
    logo: "images/mint.png",
    description: "Public Mint is a blockchain-based gaming platform.",
    socials: {
      website: "https://publicmint.com/",
      twitter: "",
      facebook: "dfa",
      instagram: "saf",
      telegram: "dsaf",
    },
  },
  {
    name: "Bitkeep",
    logo: "images/bitkeep.png",
    description: "Bitkeep is a blockchain-based gaming platform.",
    socials: {
      website: "https://bitkeep.com/",
      twitter: "",
      facebook: "dfa",
      instagram: "saf",
      telegram: "dsaf",
    },
  },
  {
    name: "Safle",
    logo: "images/safle.svg",
    description: "Safle is a blockchain-based gaming platform.",
    socials: {
      website: "https://getsafle.com/",
      twitter: "",
      facebook: "dfa",
      instagram: "saf",
      telegram: "dsaf",
    },
  },
  {
    name: "Pinknode",
    logo: "images/pinknode.jpeg",
    description: "Pinknode is a blockchain-based gaming platform.",
    socials: {
      website: "https://pinknode.io/",
      twitter: "",
      facebook: "dfa",
      instagram: "saf",
      telegram: "dsaf",
    },
  },
];
