export const ventureDetails = [
  {
    name: "Oddiyyana Ventures",
    logo: "./images/oddiyana.jpeg",
    description:
      "An investment firm focused on funding the innovation in the blockchain startup",
    socials: {
      website: "https://oddiyana.ventures/",
      twitter: "https://twitter.com/oddiyana_vc",
      facebook: "",
      instagram: "",
      telegram: "",
    },
  },
  {
    name: "V2B Labs",
    logo: "https://www.v2blabs.com/_nuxt/img/Logo.6837bc2.png",
    description:
      "A visionary R&D firm engaged in blockchain services aiming to form alliances with established businesses as well as top tier labs in the emerging industry",
    socials: {
      website: "https://www.v2blabs.com/",
      twitter: "https://mobile.twitter.com/v2blabs",
      facebook: "https://www.facebook.com/V2B2021",
      instagram: "",
      telegram: "",
    },
  },
  {
    name: "BMW Capital",
    logo: "images/bmwcapital.png",
    description:
      "BMW Capital has invested in digital assets since 2016",
    socials: {
      website: "http://www.bmw-vc.com/",
      twitter: "https://twitter.com/bmwcapital",
      facebook: "",
      instagram: "",
      telegram: "",
    },
  },
  {
    name: "Zephyrus Capital",
    logo: "https://zephyruscapital.com/wp-content/uploads/2021/12/logowhite.png",
    description:
      "A Venture Capital incorporated to help and boost the growth of Blockchain Startups",
    socials: {
      website: "https://zephyruscapital.com/",
      twitter: "https://twitter.com/CapitalZephyrus",
      facebook: "",
      instagram: "",
      telegram: "",
    },
  },
  {
    name: "Unreal Capital",
    logo: "https://static.tildacdn.com/tild3834-3661-4463-b238-393837653962/UnrealCapital_logo_v.svg",
    description:
      "An international investment Fund that supports and invests in new and promising crypto projects",
    socials: {
      website: "https://ucapital.vc/",
      twitter: "https://twitter.com/UnrealCapital",
      facebook: "",
      instagram: "",
      telegram: "https://www.instagram.com/unrealcapital_vc/",
    },
  },
  {
    name: "Next Capital",
    logo: "/images/NEXTWHTWIDE.svg",
    description:
      "Kickstarting the Future of Technology through investments in Blockchain, Web3 & Crypto",
    socials: {
      website: "https://www.nextcapital.tech/",
      twitter: "https://twitter.com/NextCapitai",
      facebook: "",
      instagram: "",
      telegram: "https://t.me/NextCapitalChat",
    },
  },
  {
    name: "Cogitent Ventures",
    logo: "/images/cogitent.png",
    description:
      "We are a pre-seed/seed level investor to empower and support gifted entrepreneurs",
    socials: {
      website: "https://cogitent.ventures/",
      twitter: "https://twitter.com/CogitentV",
      facebook: "",
      instagram: "",
      telegram: "",
    },
  },
];

export const portfolioDetails = [
  {
    name: "Aether Games",
    logo: "https://www.aethergames.io/static/media/Logo.6d355d0b397d1925df34.png",
    description: "Game Development studio",
    socials: {
      website: "https://www.aethergames.io/",
      twitter: "https://twitter.com/AetherGamesInc",
      facebook: "https://facebook.com/AetherGamesInc",
      instagram: "https://discord.gg/AetherGames",
      telegram: "https://t.me/AetherGamesAnnouncements",
    },
  },
  {
    name: "Playzap Games",
    logo: "https://uploads-ssl.webflow.com/622b71d5703c41011dd1c3ac/623294d6f64369568f797a85_footer-logo.png",
    description: "Combination of multibillion-dollar markets with Play to earn",
    socials: {
      website: "https://www.playzap.games/",
      twitter: "https://twitter.com/PlayZapGames",
      facebook: "",
      instagram: "https://discord.gg/YYPAyJpyqm",
      telegram: "https://t.me/playzap",
    },
  },
  {
    name: "Magpie",
    logo: "https://uploads-ssl.webflow.com/629b39872d72ff02443a529f/629b4145d174c694099716c5_Logo.svg",
    description:
      'Cross-chain Liquidity Aggregation',
    socials: {
      website: "https://www.magpiefi.xyz/",
      twitter: "https://twitter.com/magpieprotocol",
      facebook: "",
      instagram: "https://discord.gg/CwJuFeHp6f",
      telegram: "https://t.me/magpieprotocol",
    },
  },
  {
    name: "Web3Port",
    logo: "images/web3port.png",
    description: "Buidl Tool For Web 3 Professionals",
    socials: {
      website: "https://www.web3port.us/",
      twitter: "https://twitter.com/Web3Port_Labs",
      facebook: "",
      instagram: "",
      telegram: "",
    },
  },
  {
    name: "Astra Protocol",
    logo: "https://astraprotocol.com/wp-content/themes/astra_wp/assets/images/logo.svg",
    description: "Decentralized KYC Platform for Web3",
    socials: {
      website: "https://astraprotocol.com/",
      twitter: "https://twitter.com/AstraProtocol",
      facebook: "",
      instagram: "",
      telegram: "https://t.me/Astra_Protocol",
    },
  },
  {
    name: "Tatsumeeko",
    logo: "images/tatsumeeko.png",
    description: "Immersive modern fantasy MMORPG-lite game",
    socials: {
      website: "https://tatsumeeko.com/",
      twitter: "https://twitter.com/tatsumeeko",
      facebook: "",
      instagram: "https://discord.gg/tatsu",
      telegram: "",
    },
  },
  {
    name: "BitsCrunch",
    logo: "https://bitscrunch.com/wp-content/themes/bitscrunch/img/logo.svg",
    description: "The Guardian of the NFT ecosystem.",
    socials: {
      website: "https://bitscrunch.com/",
      twitter: "https://twitter.com/bitscrunch/",
      facebook: "https://www.facebook.com/bitsCrunch",
      instagram: "",
      telegram: "https://t.me/bitscrunch",
    },
  },
  {
    name: "Peaq Network",
    logo: "images/peaq.png",
    description: "Build, launch and scale decentralized platforms and solutions",
    socials: {
      website: "https://www.peaq.network/",
      twitter: "https://twitter.com/peaqenterprise",
      facebook: "",
      instagram: "https://discord.gg/XhJwuFKAAD",
      telegram: "https://t.me/peaqnetwork",
    },
  },
  {
    name: "ZKCross",
    logo: "images/zkcr.png",
    description: "The first multichain zkRollup utilizing zkWASM",
    socials: {
      website: "https://www.zkcross.org/",
      twitter: "https://twitter.com/thezkcross",
      facebook: "",
      instagram: "https://discord.gg/EQerNSFgqU",
      telegram: "https://t.me/ZKCross",
    },
  },
  {
    name: "Humanode",
    logo: "images/Humanode.png",
    description: "Blockchain Layer 1, using Proof-Of-Uniqueness",
    socials: {
      website: "https://humanode.io/",
      twitter: "https://twitter.com/humanode_io",
      facebook: "",
      instagram: "https://discord.com/invite/8my5gbgptx",
      telegram: "https://t.me/humanode",
    },
  },
  {
    name: "Magic Square",
    logo: "https://magicsquare.io/wp-content/uploads/2022/09/MSQ-Logo-color.svg",
    description: "The 1st Community Driven Crypto App Store",
    socials: {
      website: "https://magicsquare.io/",
      twitter: "https://twitter.com/MagicSquareio",
      facebook: "https://www.facebook.com/MagicSquareio",
      instagram: "https://discord.com/invite/Pmep3WZTyB",
      telegram: "https://t.me/magicsquare_official",
    },
  },
  {
    name: "Cosmic Guild",
    logo: "images/Cosmic.png",
    description: "The First Community Gaming Guild",
    socials: {
      website: "https://cosmicguild.io/",
      twitter: "https://twitter.com/Cosmic_Guild",
      facebook: "https://www.facebook.com/Axie-Infinity-Scholarship-Cosmic-Gaming-Guild-111363661352549",
      instagram: "https://discord.gg/cggdao",
      telegram: "http://t.me/Cosmic_guild",
    },
  },
  {
    name: "BlueMove",
    logo: "https://bluemove.net/static/media/logo-light.9e42d613ce273b89f8bd87d58adee26a.svg",
    description: "The leading NFT Marketplace on blockchain Aptos",
    socials: {
      website: "https://bluemove.net/",
      twitter: "https://twitter.com/BlueMoveNFT",
      facebook: "https://www.facebook.com/bluemove.net/",
      instagram: "https://discord.gg/PcRGces7WM",
      telegram: "https://t.me/bluemovenft",
    },
  },
  {
    name: "Mover",
    logo: "images/Mover.png",
    description: "The first bridge between EVM networks and Aptos",
    socials: {
      website: "https://mov3r.xyz/",
      twitter: "https://twitter.com/moverxyz",
      facebook: "",
      instagram: "https://discord.gg/45us2C3NBw",
      telegram: "",
    },
  },
  {
    name: "Exorde Network",
    logo: "https://uploads-ssl.webflow.com/620398f412d5829aa28fbb86/622625f35016cd6a5613f833_landscape-logo-color-white.png",
    description: "Empowers developers to crawl and link all public data",
    socials: {
      website: "https://exorde.network/",
      twitter: "https://twitter.com/ExordeLabs",
      facebook: "https://facebook.com/exordelabs",
      instagram: "https://discord.com/invite/5XdUGbThaw",
      telegram: "https://t.me/exordelabs",
    },
  },

  {
    name: "Alterverse",
    logo: "https://alterverse.com/wp-content/uploads/2021/01/AlterVerseLogo_Lg_White_NoStroke_400.png",
    description: "An expansive Metaverse game experience",
    socials: {
      website: "https://alterverse.com/",
      twitter: "https://www.twitter.com/alterversegame",
      facebook: "https://www.facebook.com/alterversegame",
      instagram: "https://discord.com/invite/yf7bCzz",
      telegram: "https://t.me/alterverse",
    },
  },

  {
    name: "Entangle Finance",
    logo: "images/entangle.png",
    description: "Cross-Chain Liquidity DApps Powered by Synthetic Derivatives",
    socials: {
      website: "https://entangle.fi/",
      twitter: "https://twitter.com/Entanglefi",
      facebook: "",
      instagram: "https://discord.gg/xXSvMRZPsb",
      telegram: "https://t.me/+oh2SozgECncwZTQ0",
    },
  },
  {
    name: "Taker Protocol",
    logo: "images/taker.png",
    description: "The First DAO-based Liquidity for Novel NFT Assets",
    socials: {
      website: "https://taker.org/",
      twitter: "https://twitter.com/TakerProtocol",
      facebook: "",
      instagram: "https://discord.gg/taker",
      telegram: "https://t.me/taker_protocol",
    },
  },
  {
    name: "Aptin Finance",
    logo: "images/aptin.png",
    description: "Advanced Lending Protocol On Aptos",
    socials: {
      website: "https://aptin.io/",
      twitter: "https://twitter.com/aptinlabs",
      facebook: "",
      instagram: "https://discord.gg/fMVkQNumzb",
      telegram: "https://t.me/aptinlabs",
    },
  },
];

export const partnerDetails = [
  {
    name: "Celer Network",
    logo: "images/celer.png",
    description: "Building the best inter-blockchain and cross-layer communication platform",
    socials: {
      website: "https://cbridge.celer.network/",
      twitter: "https://twitter.com/CelerNetwork",
      facebook: "",
      instagram: "",
      telegram: "https://t.me/celernetwork",
    },
  },
  {
    name: "China Polka",
    logo: "images/chinapolka.png",
    description: "Unofficial non-profit Chinese Polka Community Alliance organized independently",
    socials: {
      website: "http://chinapolka.com/",
      twitter: "",
      facebook: "",
      instagram: "",
      telegram: "",
    },
  },
  {
    name: "Polygon",
    logo: "images/polygon.png",
    description: "A global & sustainable Web3 infrastructure built on Ethereum",
    socials: {
      website: "https://polygon.technology/",
      twitter: "https://twitter.com/0xPolygon",
      facebook: "",
      instagram: "https://discord.gg/0xPolygon",
      telegram: "https://t.me/polygonofficial",
    },
  },
  {
    name: "TomoChain",
    logo: "images/tmochain.svg",
    description: "The Efficient Blockchain Powered by Proof of Stake Voting Consensus",
    socials: {
      website: "https://tomochain.com/",
      twitter: "https://twitter.com/TomoChainANN",
      facebook: "https://www.facebook.com/tomochainofficial",
      instagram: "",
      telegram: "https://t.me/TomoChainChannel",
    },
  },
  {
    name: "Casper Labs",
    logo: "images/casper.png",
    description: "The First Blockchain Built for Enterprise Adoption",
    socials: {
      website: "https://casperlabs.io/",
      twitter: "https://twitter.com/Casper_Network",
      facebook: "",
      instagram: "https://discord.com/invite/Q38s3Vh",
      telegram: "https://t.me/casperblockchain",
    },
  },
  {
    name: "Certik",
    logo: "https://movenetwork.io/wp-content/uploads/2021/11/Certik-logo-300x300-01.png",
    description: "Best-in-class tech from academia to enterprise, ensuring accuracy & security of your blockchain projects",
    socials: {
      website: "https://certik.com/",
      twitter: "https://twitter.com/CertiK",
      facebook: "",
      instagram: "",
      telegram: "https://t.me/CertiKCommunity",
    },
  },
  {
    name: "Hacken",
    logo: "https://s2.coinmarketcap.com/static/img/coins/200x200/5583.png",
    description: "WEB3 CYBERSECURITY AUDITOR",
    socials: {
      website: "https://hacken.io/",
      twitter: "https://twitter.com/hackenclub",
      facebook: "",
      instagram: "https://discord.gg/VYJXut8huR",
      telegram: "https://t.me/hackenio",
    },
  },
  {
    name: "Koi Starter",
    logo: "images/koistarter.svg",
    description: "A cutting-edge and secure launchpad powered by Creator Platform",
    socials: {
      website: "https://koistarter.io/",
      twitter: "https://discord.gg/VYJXut8huR",
      facebook: "",
      instagram: "",
      telegram: "https://t.me/KoiStarterlaunchpad",
    },
  },
  {
    name: "Harmony Launcher",
    logo: "images/harmony-launcher.jpg",
    description: "the first Decentralized IGO + IDO Incubation Launchpad on Harmony Blockchain",
    socials: {
      website: "https://harmonylauncher.io/",
      twitter: "https://twitter.com/harmonylauncher",
      facebook: "",
      instagram: "",
      telegram: "https://t.me/harmonylauncher",
    },
  },
  {
    name: "Kommunitas",
    logo: "images/kommunitas.png",
    description: "Decentralized Crowdfunding Ecosystem for Web3 projects",
    socials: {
      website: "https://kommunitas.net/",
      twitter: "https://twitter.com/kommunitas1",
      facebook: "",
      instagram: "https://discord.com/invite/hasFnzJbfp",
      telegram: "https://t.me/Kommunitas_Ann",
    },
  },
  {
    name: "Fantom Live",
    logo: "images/fantomlive.png",
    description: "The First Web 3.0 Livestream- Metaverse & Launchpad",
    socials: {
      website: "https://fantomlive.finance/",
      twitter: "https://twitter.com/FantomLiveS",
      facebook: "",
      instagram: "",
      telegram: "http://t.me/FantomLive_Chat ",
    },
  },
  {
    name: "Unifarm",
    logo: "images/unifarm.jpg",
    description: "One farm to rule them all - Stake one token, farm many! ",
    socials: {
      website: "https://unifarm.co/",
      twitter: "https://twitter.com/unifarm_",
      facebook: "",
      instagram: "https://rebrand.ly/DiscordUFARM",
      telegram: "https://telegram.me/myunifarm",
    },
  },
  {
    name: "Unilend",
    logo: "images/unilend.png",
    description: "Multichain protocol for Lending & Borrowing all ERC20 tokens",
    socials: {
      website: "https://unilend.finance/",
      twitter: "https://twitter.com/UniLend_Finance",
      facebook: "",
      instagram: "https://www.reddit.com/r/UniLend/",
      telegram: "https://t.me/UniLendFinance",
    },
  },
  {
    name: "Ankr",
    logo: "images/ankr.png",
    description: "The fastest, most reliable Web3 infrastructure",
    socials: {
      website: "https://ankr.com/",
      twitter: "https://twitter.com/ankr",
      facebook: "",
      instagram: "https://discord.gg/ankr",
      telegram: "https://t.me/ankrnetwork",
    },
  },
  {
    name: "Dfyn Network",
    logo: "images/dfyn.png",
    description: "Multi-Chain DEX",
    socials: {
      website: "https://dfyn.network/",
      twitter: "https://twitter.com/_dfyn",
      facebook: "",
      instagram: "https://discord.gg/yjM2fUUHvN",
      telegram: "https://t.me/Dfyn_HQ",
    },
  },
  {
    name: "Bitkeep",
    logo: "images/bitkeep.png",
    description: "An easy-to-use Web3 wallet",
    socials: {
      website: "https://bitkeep.com/",
      twitter: "https://twitter.com/BitKeepOS",
      facebook: "https://www.facebook.com/BitKeep",
      instagram: "https://discord.gg/au3GJCe5Wc",
      telegram: "https://t.me/bitkeep",
    },
  },
  {
    name: "Safle",
    logo: "images/safle.svg",
    description: "Non-custodial, multi-chain wallet and blockchain infra",
    socials: {
      website: "https://getsafle.com/",
      twitter: "https://twitter.com/GetSafle",
      facebook: "",
      instagram: "https://discord.gg/aj9YRCfh26",
      telegram: "https://t.me/safleann",
    },
  },
  {
    name: "Pinknode",
    logo: "images/pinknode.jpeg",
    description: "The Gateway To The Polkadot Ecosystem",
    socials: {
      website: "https://pinknode.io/",
      twitter: "https://twitter.com/official_pnode",
      facebook: "",
      instagram: "",
      telegram: "https://t.me/pinknode",
    },
  },
];
